# inventory for UAT Testing Env
# Usage: 
#     - ansible-playbook -i inventory/uat-dev.ini mysql-install.yml
#     - ansible-playbook -i inventory/uat-dev.ini mysql-setup.yml

[mysql]
192.158.200.2

[emis-server]
192.168.200.2

[mysql:vars]
mysql_host=127.0.0.1
mysql_port=3306
mysql_user=root
mysql_password=root

mysql_user_emis=emis-user
mysql_user_emis_password=EmisUser09
mysql_emis_dbname=emis-uat

mysql_user_configured=wso2user
mysql_user_configured_password=Wso2User@987
mysql_apim_db=wso2_apim_db
mysql_apim_shared_db=wso2_apim_shared_db
mysql_is_db=wso2_is_db
mysql_is_shared_db=wso2_is_shared_db
