---
# ---PLAY-DEPLOY-FRONTEND-----
- name: Deploy EMIS UAT — Frontend Only
  hosts: frontend_service
  become: true
  vars:
    remote_project_path: "/opt/emis-uat"
    docker_compose_file: "{{ playbook_dir | dirname }}/docker/docker-compose.yml"
  vars_files:
    - vars_files/vars.yml

  tasks:
    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ remote_project_path }}"
        state: directory
        mode: '0755'

    - name: Render and copy frontend env file
      ansible.builtin.template:
        src: "templates/frontend.env.j2"
        dest: "{{ remote_project_path }}/frontend.env"
        mode: '0600'

    - name: Render and copy docker env file
      ansible.builtin.template:
        src: "templates/docker.env.j2"
        dest: "{{ remote_project_path }}/.env"
        mode: '0600'

    - name: Copy Docker Compose file
      ansible.builtin.copy:
        src: "{{ docker_compose_file }}"
        dest: "{{ remote_project_path }}/docker-compose.yml"
        mode: '0644'

    - name: Pull and start frontend container only
      community.docker.docker_compose_v2:
        project_src: "{{ remote_project_path }}"
        services:
          - frontend             # ← only the frontend service from compose file
        state: present
        pull: always
      register: output

    - name: Show Docker Compose output
      ansible.builtin.debug:
        var: output
