services:
  # WSO2 Identity Server
  wso2-is:
    image: "${WSO2_IS_DOCKERIMG_REPO}:${WSO2_IS_DOCKERIMG_TAG}"
    container_name: is-host
    ports:
      - "9444:9444" # Offset 1 makes the internal port 9444
#    volumes:
#      - type: bind
#        source: /opt/emis-uat/wso2-is/deployment.toml
#        target: /home/wso2carbon/wso2is-7.2.0/repository/conf/deployment.toml
    environment:
      - WSO2_SERVER_OFFSET=1
    networks:
      - uat-emis-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # WSO2 API Manager
  wso2-apim:
    image: "${WSO2_APIM_DOCKERIMG_REPO}:${WSO2_APIM_DOCKERIMG_TAG}"
    container_name: apim-host
    ports:
      - "9443:9443" # Management Portal / Carbon
      - "8243:8243" # HTTPS Gateway
      - "8280:8280" # HTTP Gateway
#    volumes:
#      - type: bind
#        source: /opt/emis-uat/wso2-am/deployment.toml
#        target: /home/wso2carbon/wso2am-4.6.0/repository/conf/deployment.toml   
    networks:
      - uat-emis-network
    depends_on:
      - wso2-is
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend
  frontend:
    image: "${FRONTEND_DOCKERIMG_REPO}:${FRONTEND_DOCKERIMG_TAG}" # -> .env
    container_name: hrm-uat-frontend
    env_file:
      - frontend.env # FRONTEND ENV
    ports:
      - "80:80" 
    networks:
      - uat-emis-network

  # Backend
  backend:
    image: "${BACKEND_DOCKERIMG_REPO}:${BACKEND_DOCKERIMG_TAG}" # -> .env
    container_name: hrm-uat-backend
    command: >
      sh -c "composer install --no-interaction &&
             cp backend.env .env &&
             php artisan migrate:fresh --seed --force &&
             php-fpm"
    ports:
      - "9000:9000" # temp backend exposure
    volumes:
      - /opt/emis-uat/backend.env:/var/www/html/backend.env 
    env_file:
      - backend.env # BACKEND ENV
    networks:
      - uat-emis-network
    extra_hosts:
      - "host.docker.internal:host-gateway"


# Isolated custom network
networks:
  uat-emis-network:
    driver: bridge
    name: hrm-uat-network
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
