[server]
hostname = "$env{APIM_HOSTNAME}"
base_path = "https://${carbon.host}"
server_role = "default"

[transport.https.properties]
proxyHost = "$env{APIM_HOSTNAME}"      # same as your public hostname
proxyPort = "443"                       # hardcode this, it won't change

[super_admin]
username = "$env{APIM_ADMIN_USERNAME}"
password = "$env{APIM_ADMIN_PASSWORD}"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://$env{APIM_DB_HOST}:$env{APIM_DB_PORT}/$env{APIM_DB_APIMDB}?useSSL=false&amp;allowPublicKeyRetrieval=true&amp;autoReconnect=true"
username = "$env{APIM_DB_WSO2USER_USERNAME}"
password = "$env{APIM_DB_WSO2USER_PASSWORD}"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://$env{APIM_DB_HOST}:$env{APIM_DB_PORT}/$env{APIM_DB_SHARED}?useSSL=false&amp;allowPublicKeyRetrieval=true&amp;autoReconnect=true"
username = "$env{APIM_DB_WSO2USER_USERNAME}"
password = "$env{APIM_DB_WSO2USER_PASSWORD}"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

# ----------
#  GATEWAY
# ----------

[apim]
gateway_type = "Regular,APK,AWS,Azure,Kong,Envoy"

[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default"]

[[apim.gateway.environment]]
name = "Default"
type = "hybrid"
gateway_type = "Regular"
provider = "wso2"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url = true
service_url = "https://localhost:${mgt.transport.https.port}/services/"
username= "$env{APIM_ADMIN_USERNAME}"
password= "$env{APIM_ADMIN_PASSWORD}"
ws_endpoint = ""
wss_endpoint = ""
http_endpoint = ""
https_endpoint = "https://$env{APIM_GATEWAY_URL}"
websub_event_receiver_http_endpoint = ""
websub_event_receiver_https_endpoint = "https://$env{APIM_GATEWAY_URL}"

# --------
# Portals
# -------

[apim.devportal]
url = "https://$env{APIM_HOSTNAME}/devportal"

[apim.publisher]
url = "https://$env{APIM_HOSTNAME}/publisher"


# ----------
#   IDP - (Internal Portal Authentication)
# ----------

[apim.key_manager]
service_url = "https://$env{APIM_IS_HOST}:$env{APIM_IS_PORT}/services/"
username = "$env{APIM_IS_KEYMANAGER_USERNAME}"
password = "$env{APIM_IS_KEYMANAGER_PASSWORD}"
type = "WSO2-IS"

[apim.idp]
server_url = "https://$env{APIM_IS_HOST}:$env{APIM_IS_PORT}"
authorize_endpoint = "https://$env{APIM_IS_HOSTNAME}/oauth2/authorize"
oidc_logout_endpoint = "https://$env{APIM_IS_HOSTNAME}/oidc/logout"
oidc_check_session_endpoint = "https://$env{APIM_IS_HOSTNAME}/oidc/checksession"


# ----------------
#  Health Checks
# ---------------

[carbon_health_check]
enable= true

[carbon_health_check.health_checker.data_source_health_checker.properties]
'monitored.datasources' = "jdbc/WSO2CarbonDB,jdbc/WSO2UM_DB,jdbc/SHARED_DB"

[carbon_health_check.health_checker.super_tenant_health_checker.properties]
'monitored.user.stores' = "primary"


# -----------
#  Other
# ----------

[apim.analytics]
enable = false
type = "moesif"

[apim.ai]
enable = false
key = ""

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","apikey","Internal-Key"]
allow_credentials = false

[apim.throttling]
enable_data_publishing = false
enable_policy_deploy = false
enable_blacklist_condition = false
enable_persistence = false
#throttle_decision_endpoints = ["tcp://localhost:5672","tcp://localhost:5672"]

[transport.jms]
listener.enable = false
