---
all:
  vars:
    ansible_user: slaf-dhaki
    ansible_private_key_file: /var/home/dhakiweere/.ssh/emis_vmaccess_ed25519

  children:

    # ── Jumpbox (public-facing, no proxy hop) ───────────────────────
    jumpbox:
      hosts:
        uat-jump:
          ansible_host: 124.43.177.235
          ansible_user: slaf-dhaki
          ansible_private_key_file: /var/home/dhakiweere/.ssh/emis_vmaccess_ed25519
          ansible_ssh_common_args: ""

    # ── All private hosts (routed through jumpbox) ──────────────────
    private_hosts:
      vars:
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o ProxyJump=slaf-dhaki@124.43.177.235
      children:

        swarm_managers:
          hosts:
            uat-node:
              ansible_host: 192.168.200.5

        swarm_workers:
          hosts:
            uat-node:              # same VM — manager is also its own worker
              ansible_host: 192.168.200.5

        db_host:
          hosts:
            uat-db:              # MySQL on bare metal of db  VM
              ansible_host: 192.168.200.6
