name: Build and Push Backend
run-name: "Build & Push backend image on ${{ github.ref_name }}"
on:
  workflow_dispatch: # trigger workflow manually
  workflow_call:    # trigger workflow from an external workflow
    inputs:
      version:
        type: string
        required: false
        default: ""
    outputs:
      image_built:
        description: "Whether a new Docker image was actually built and pushed"
        value: ${{ jobs.build-backend.outputs.image_built }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      image_built: ${{ steps.build_image.outcome == 'success' }}
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY_BASE: "ghcr.io/emis-moe-gov-lk/emis-backend"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract Backend Version
        id: get_version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${{ vars.BACKEND_VERSION }}"
          fi
          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if Tag Exists in GHCR
        id: ghcr_check
        run: |
          TARGET_IMAGE="${{ env.REGISTRY_BASE }}:${{ steps.get_version.outputs.version }}"
          echo "Checking if $TARGET_IMAGE exists in GHCR..."
          
          if docker manifest inspect $TARGET_IMAGE > /dev/null 2>&1; then
            echo "Image tag ${{ steps.get_version.outputs.version }} already exists in GHCR."
            echo "should_build=false" >> $GITHUB_OUTPUT
          else
            echo "Image tag ${{ steps.get_version.outputs.version }} not found. Proceeding with build."
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi
      - name: Build and push Backend image
        id: build_image
        if: steps.ghcr_check.outputs.should_build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY_BASE }}:${{ steps.get_version.outputs.version }}
            ${{ env.REGISTRY_BASE }}:latest
